# Generated by Django 2.2.1 on 2019-08-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainishadiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
